# syntax = docker/dockerfile:1

ARG RUBY_VERSION=3.3.1
FROM registry.docker.com/library/ruby:$RUBY_VERSION-slim

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y curl

# Install Node.js
ARG NODE_VERSION=22.0.0
ENV PATH=/usr/local/node/bin:$PATH
RUN curl -sL https://github.com/nodenv/node-build/archive/master.tar.gz | tar xz -C /tmp/ && \
    /tmp/node-build-master/bin/node-build "${NODE_VERSION}" /usr/local/node && \
    rm -rf /tmp/node-build-master

WORKDIR /rails

RUN npm install tailwindcss flowbite

COPY <<EOF tailwind.config.js
module.exports = {
    plugins: [
        require('flowbite/plugin')
    ]
}
EOF

RUN node tailwind.config.js